/**
 * Cross-language conformance check.
 *
 * Reads the fixtures generated by the Python implementation and asserts the
 * JS port reproduces them byte for byte. If this fails, the two runtimes
 * disagree and the whole portability claim is void — so this runs in CI.
 */
import { readFileSync } from 'node:fs';
import {
  derive, deriveHex, deriveFloats, deriveInts, deriveShuffle,
} from '../contrib/lufs-seed-derive.mjs';

const vec = JSON.parse(readFileSync(new URL('./fixtures/derivation-vectors.json', import.meta.url)));
const seed = vec.seed_hex;
let pass = 0;
let fail = 0;

function check(name, ok, detail = '') {
  if (ok) { pass++; console.log(`[PASS] ${name}`); }
  else { fail++; console.log(`[FAIL] ${name} ${detail}`); }
}

for (const t of vec.bytes) {
  const got = await deriveHex(seed, t.label, t.length);
  check(`bytes label=${JSON.stringify(t.label)} len=${t.length}`,
    got === t.hex, `\n  py=${t.hex.slice(0, 32)}...\n  js=${got.slice(0, 32)}...`);
}

for (const t of vec.floats) {
  const got = await deriveFloats(seed, t.label, t.count);
  const ok = got.length === t.values.length && got.every((v, i) => v === t.values[i]);
  check(`floats label=${t.label} n=${t.count}`, ok,
    `\n  py=${JSON.stringify(t.values)}\n  js=${JSON.stringify(got)}`);
}

for (const t of vec.ints) {
  const got = await deriveInts(seed, t.label, t.count, t.min, t.max);
  const ok = got.length === t.values.length && got.every((v, i) => v === t.values[i]);
  check(`ints label=${t.label} [${t.min},${t.max}]`, ok,
    `\n  py=${JSON.stringify(t.values)}\n  js=${JSON.stringify(got)}`);
}

for (const t of vec.shuffle) {
  const got = await deriveShuffle(seed, t.label, t.items);
  const ok = JSON.stringify(got) === JSON.stringify(t.result);
  check(`shuffle label=${t.label}`, ok,
    `\n  py=${JSON.stringify(t.result)}\n  js=${JSON.stringify(got)}`);
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
